#!/bin/sh

[ -f "$PWD"/qemu-vm.img ] || {
  qemu-img create -f qcow2 "$PWD"/qemu-vm.img 50G
}

qemu-system-x86_64 -enable-kvm \
  		   -cpu host \
		   -machine q35 \
		   -drive file="$PWD"/qemu-vm.img,id=disk,if=none \
		   -device ahci,id=ahci \
		   -device ide-hd,drive=disk,bus=ahci.0 \
		   -device virtio-rng-pci \
		   -m 2G \
		   -smp 4 \
		   -nographic \
		   -name "LIVE LINUX VM" \
		   -boot d \
		   -cdrom $@



rm -f "$PWD"/qemu-vm.img
exit 0
